name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'Apicurio'
    steps:

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build
        run: |
          ./prod-build.sh

      - name: Push container image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push quay.io/apicurio/apicurio-registry-mt-ui:latest

      - name: Push container image
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        run: |
          docker tag quay.io/apicurio/apicurio-registry-mt-ui:latest quay.io/apicurio/apicurio-registry-mt-ui:${GITHUB_REF##*/}
          docker push quay.io/apicurio/apicurio-registry-mt-ui:${GITHUB_REF##*/}
