name: CI Workflow

on:
  pull_request:
    branches: [ main ]

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.repository_owner, 'bf2fc6cc711aee1a0c2a')
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node-version}}

      - name: Installing dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run production build
        run: npm run build
